version: "3"

services:
  learners:
    image: ghcr.io/ait-cs-iaas/learners
    ports:
      - "${LEARNERS_PORT:-8080}:8080"
    environment:
      - REMOVE_DB=${REMOVE_DB}
    volumes:
      - type: bind
        source: ./rendered_hugo_content/exercises
        target: /opt/learners/webroot/static/exercises
      - type: bind
        source: ./rendered_hugo_content/documentation
        target: /opt/learners/webroot/static/documentation
      - ./learners_data:/opt/learners/data

volumes:
  learners_data:
