version: "3"

services:
  learners:
    image: ghcr.io/ait-cs-iaas/learners
    ports:
      - "${LEARNERS_PORT:-8080}:8080"
    volumes:
      - "learners_exercises:/opt/learners/webroot/exercises"
      - "learners_documentation:/opt/learners/webroot/documentation"
      - "learners_data:/opt/learners/data"

volumes:
  learners_exercises:
  learners_documentation:
  learners_data:
