learners:
  theme: "dark"
  landingpage: "novnc"

jwt:
  jwt_secret_key: "53CR3T"
#   jwt_for_vnc_access: False

database:
  db_uri: "sqlite:///data.db"

# venjix:
#   auth_secret: "53CR3T"
#   url: "http://localhost:5001"

statics:
  directory: "static"
  serve_mode: "role"

exercise_json: "static/hugo/exercises.json"
questionaire_json: "static/hugo/questionaires.json"
questionaires_questions_json: "static/hugo/questionaires_questions.json"

serve_documentation: True
serve_exercises: True
serve_presentations: True

# staticsites:
#   - url: "/statics/staticsite"
#     id: "mitre"
#     title: "test site"
#     icon: "icon_mitre"
#   - url: "/statics/staticsite"
#     id: "drawio"
#     title: "draw io site"
#     icon: "icon_drawio"
#   - url: "/statics/staticsite"
#     id: "testsite"
#     title: "std site"
#     icon: "icon_doc"

# callback:
#   endpoint: "http://localhost:5000/callback"

novnc:
  server: "http://localhost:8888"

users:
  test:
    password: test
    role: instructor
    vnc_clients:
      soc_client:
        target: placeholder_1
        tooltip: "SOC client"
        username: csirt1
        password: placeholder
      pps_client:
        target: placeholder_3
        tooltip: "PPS client"
        username: csirt3
        password: placeholder
  ben:
    password: ben
    # vnc_clients:
    #   soc_client:
    #     target: placeholder_2
    #     tooltip: "SOC client"
    #     username: csirt2
    #     password: placeholder
  admin:
    password: admin
    admin: True
