headline: "Welcome to the"
headlineHighlight: "CyberRange"
welcomeText: "This is the entry point to the virtual environment of the simulation.<br>Please log in with your assigned credentials:"

primary: "#4510aa"
