# learners:
  # htpasswd: "temp_htpasswd"
  # theme: "dark"

jwt:
  jwt_secret_key: "53CR3T"
  jwt_for_vnc_access: False

database:
  db_uri: "sqlite:///learners_tracker.db"

# mail:
#   server: ""
#   port: 587
#   username: ""
#   password: ""
#   tls: True
#   ssl: False


venjix:
  auth_secret: "53CR3T"
  url: "http://localhost:5001"

documentation:
  directory: "static/documentation"
  endpoint: "/documentation"

exercises:
  directory: "static/exercises"
  endpoint: "/exercises"

callback:
  endpoint: "/callback"

novnc:
  server: "10.17.5.119"

users:
  test:
    password: test
    vnc_clients:
      soc_client:
        target: placeholder_1
        tooltip: "SOC client"
        username: csirt1
        password: placeholder
      pps_client:
        target: placeholder_3
        tooltip: "PPS client"
        username: csirt3
        password: placeholder
  ben:
    password: ben
    vnc_clients:
      soc_client:
        target: placeholder_2
        tooltip: "SOC client"
        username: csirt2
        password: placeholder
  admin:
    is_admin: True
    password: admin
