learners:
  theme: "dark"

jwt:
  jwt_secret_key: "53CR3T"

database:
  db_uri: "sqlite:///learners_tracker.db"

documentation:
  directory: "static/documentation"
  endpoint: "/documentation"

exercises:
  directory: "static/exercises"
  endpoint: "/exercises"

presentation:
  url: "https://localhost:8443/anothertest"

callback:
  endpoint: "http://localhost:5000/callback"

users:
  test:
    password: test
  user1:
    password: user1
  user2:
    password: user2
  admin:
    admin: True
    password: admin

# mail:
#   server: ""
#   port: 587
#   username: ""
#   password: ""
#   tls: True
#   ssl: False

# venjix:
#   auth_secret: "53CR3T"
#   url: "http://localhost:5001"


# novnc:
#   server: "http://localhost:5002"

# screenSharing: True

# users:
#   test:
#     password: test
#     # is_presenter: True
#     vnc_clients:
#       soc_client:
#         target: placeholder_1
#         tooltip: "SOC client"
#         username: csirt1
#         password: placeholder
#       pps_client:
#         target: placeholder_3
#         tooltip: "PPS client"
#         username: csirt3
#         password: placeholder
#   ben:
#     password: ben
#     vnc_clients:
#       soc_client:
#         target: placeholder_2
#         tooltip: "SOC client"
#         username: csirt2
#         password: placeholder
#   admin:
#     admin: True
#     password: admin
