learners:
  htpasswd: "temp_htpasswd"
  # theme: "light"

jwt:
  jwt_secret_key: "53CR3T"
  jwt_for_vnc_access: False

database:
  db_uri: "sqlite:///learners_tracker.db"

# mail:
#   server: ""
#   port: 587
#   username: ""
#   password: ""
#   tls: True
#   ssl: False

components:
  venjix_auth_secret: "53CR3T"
  urls:
    venjix: "http://127.0.0.1:5001"
    callback: "http://127.0.0.1:5000/callback"
    documentation: "http://localhost"
    exercises: "http://localhost"
    novnc: "10.17.4.219"
  user_assignments:
    test:
      vnc_clients:
        soc_client:
          target: 1
          tooltip: "SOC client"
          username: csirt1
          password: placeholder
        pps_client:
          target: 3
          tooltip: "PPS client"
          username: csirt3
          password: placeholder
      ports:
        docs: 8080
        exercises: 8888
    ben:
      vnc_clients:
        soc_client:
          target: 1
          tooltip: "SOC client"
          username: csirt2
          password: placeholder
      ports:
        docs: 8080
        exercises: 8888
