DEBUG: False
TESTING: False
LEARNERS_HTPASSWD: "temp_htpasswd"
VENJIX_AUTH_SECRET: "53CR3T"
JWT_SECRET_KEY: "53CR3T"
JWT_TOKEN_LOCATION: ['headers', 'cookies']
JWT_ACCESS_TOKEN_DURATION: 120
THEME: "dark"
BRANDING: True
CORS_HEADERS: "Content-Type"
CORS_ORIGINS: ['http://127.0.0.1:8888', 'http://localhost:8080', 'http://127.0.0.1:8080', 'http://localhost:8888']
CORS_SUPPORTS_CREDENTIALS: True
SQLALCHEMY_DATABASE_URI: "sqlite:///learners_tracker.db"
SQLALCHEMY_TRACK_MODIFICATIONS: False
LANGUAGE: "en"

VENJIX_URL: "http://127.0.0.1:5001"
VNC_URLS: [
  ["https://placeholder_1@10.17.4.219/"], 
  ["https://placeholder_3@10.17.4.219/", "PPS"]
  ]
CALLBACK_URL: "http://127.0.0.1:5000/callback"
DOCS_URL: "http://localhost"
EXERCISES_URL: "http://localhost"

PORT_LIST: 
  test:
    docs: "8080"
    exercises: "8888"
  ben: 
    docs: "8080"
    exercises: "8888"