from backend.routes.admin import admin_api
from backend.routes.authentication import authentication_api
from backend.routes.callback import callback_api
from backend.routes.execution import execution_api
from backend.routes.comment import comment_api
from backend.routes.home import home_api
from backend.routes.interface import interface_api
from backend.routes.notification import notification_api
from backend.routes.statics import statics_api
from backend.routes.setup import setup_api
