# learners:
  # theme: "dark"

jwt:
  jwt_secret_key: "53CR3T"
  jwt_for_vnc_access: False

database:
  db_uri: "sqlite:////opt/learners/data/learners_tracker.db"

documentation:
  directory: "/opt/learners/webroot/documentation"
  endpoint: "/documentation"

exercises:
  directory: "/opt/learners/webroot/exercises"
  endpoint: "/exercises"

callback:
  endpoint: "http://localhost:8080/callback"

venjix:
  auth_secret: "53CR3T"
  url: "http://localhost:5001"

novnc:
  server: "http://localhost:5002"

screenSharing: True

users:
  test:
    password: test
    is_presenter: True
  user1:
    password: user1
  user2:
    password: user2
  user3:
    password: user3
  admin:
    is_admin: True
    password: admin
