version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl/
    depends_on:
      - learners
  learners:
#   image: ghcr.io/ait-cs-iaas/learners
    build:
      context: ./learners
      dockerfile: ./Dockerfile
      args:
        LEARNERS_VERSION: ${LEARNERS_VERSION:-0.5.2}
        LEARNERS_BRANCH: ${LEARNERS_BRANCH:-master}
        LEARNERS_CONFIG: ${LEARNERS_CONFIG:-/opt/learners/data/config.yml}
    container_name: learners
    restart: always
    ports:
      - 8080:8080
    environment:
      - REMOVE_DB=${REMOVE_DB:-False}
    volumes:
      - type: bind
        source: ./learners/__webroot
        target: /opt/learners/webroot
      - type: bind
        source: ./learners/__data
        target: /opt/learners/data

      - ./learners/__templates/theme_iaea.scss:/opt/learners/.local/lib/python3.10/site-packages/learners/static/css/theme_iaea.scss
      - ./learners/__templates/logo.html:/opt/learners/.local/lib/python3.10/site-packages/learners/templates/partials/logo.html
      - ./learners/__templates/login.html:/opt/learners/.local/lib/python3.10/site-packages/learners/templates/login.html
