name: CI/CD

on: [push, pull_request]
jobs:
  lint:
    name: lint & check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Lint with flake8
        run: |
          flake8 learners --count --exit-zero --max-complexity=10 --max-line-length=142 --statistics
      - name: lint with black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
