name: CI/CD

on:
  push:
    branches:
    - master
  pull_request:
jobs:
  lint:
    name: lint & check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
      - name: Lint with flake8
        run: |
          flake8 learners --count --exit-zero --max-complexity=10 --max-line-length=142 --statistics
      - name: lint with black
        uses: rickstaa/action-black@v1
        with:
          black_args: "learners --check"
